# Generated by Django 4.2.2 on 2023-07-04 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0002_user_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommessage',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='modelCore.match'),
        ),
    ]
