# Generated by Django 4.2.2 on 2023-07-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0003_chatroommessage_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomusership',
            name='is_create',
            field=models.BooleanField(default=False),
        ),
    ]
