# Generated by Django 4.2.2 on 2023-07-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0004_chatroomusership_is_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
