# Generated by Django 4.2.2 on 2023-07-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0006_user_about_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroommessage',
            old_name='user',
            new_name='sender',
        ),
    ]
