# Generated by Django 4.2.2 on 2023-08-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0013_interest_alter_userimage_user_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlike',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
