# Generated by Django 4.2.2 on 2023-08-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelCore', '0014_userlike_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='is_like',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
